application: esei-infra-ticket
version: 1
runtime: python27
api_version: 1
threadsafe: yes

inbound_services:
- mail

handlers:
- url: /favicon\.ico
  static_files: res/favicon.ico
  upload: favicon\.ico

- url: /templates
  static_dir: templates
  application_readable: true

- url: /res
  static_dir: res

- url: /error
  script: handlers.error.app

- url: /info
  script: handlers.info.app

- url: /report
  script: handlers.report.app
  login: admin

- url: /users
  script: handlers.users.manage.app
  login: required

- url: /users/add
  script: handlers.users.add.app
  login: required

- url: /users/modify/(\d+)
  script: handlers.users.modify.app
  login: required

- url: /users/delete
  script: handlers.users.delete.app
  login: required

- url: /tickets(/\d*)?
  script: handlers.tickets.manage.app
  login: required

- url: /tickets/view/(.+)
  script: handlers.tickets.view.app
  login: required

- url: /tickets/add
  script: handlers.tickets.add.app
  login: required

- url: /tickets/toner
  script: handlers.tickets.toner.app
  login: required

- url: /tickets/modify/(\d+)
  script: handlers.tickets.modify.app
  login: required

- url: /tickets/delete
  script: handlers.tickets.delete.app
  login: required

- url: /_ah/mail/.+
  script: handlers.manage_incoming_email.app
  login: admin

- url: /
  script: handlers.welcome.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
